### ISSUE TITLE
`data:post.title ?: data:messages.noTitle` does not work

### ISSUE THREAD

**Issue by igoynawamreh** [blogger-starter/bloggerable#3]
PR: #1 

The `data:messages.noTitle` not showing when title (`data:post.title`) empty. 🤔

@tovic

**Comment by tovic** [comment]
Sigh, maybe the `?:` operator is not the same with PHP&rsquo;s `?:` and instead, it is equal to the `??` operator which will return the next expression if previous expression is `null`.

But, FYI the `?:` has been found in the default **Contempo** theme:

![2018-05-09-17-33-14](https://user-images.githubusercontent.com/1669261/39810552-93c57738-53af-11e8-9112-1f21c2ab3dbb.png)
